### ISSUE TITLE
ipfix constantly crashes

### ISSUE THREAD

**Issue by digitalpilotnm** [manitonetworks/flowanalyzer#2]
Hi,  infix is crashing about every 30 seconds.

Traceback (most recent call last):
  File "./ipfix.py", line 431, in <module>
    helpers.bulk(es,flow_dic)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 195, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 163, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 135, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: (u'1 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'Flow', u'_id': u'AVyTE_avwlw_IxAFa81b', u'error': {u'caused_by': {u'reason': u'Numeric value (4294967295) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@7190f04; line: 1, column: 905]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [Destination AS]', u'type': u'mapper_parsing_exception'}, u'_index': u'flow-2017-06-10'}}])

**Comment by Mutahhar-Nets** [comment]
Kindly do share the solution of it thanks
